

-- SQL_VARIANT_PROPERTY
SELECT SQL_VARIANT_PROPERTY(10, -- value
							'BaseType') -- discover type

SELECT SQL_VARIANT_PROPERTY(10.99, 'BaseType')
SELECT SQL_VARIANT_PROPERTY('CFCG', 'BaseType')
SELECT SQL_VARIANT_PROPERTY('2001-07-12', 'BaseType')

-- CAST

SELECT CAST(10.999 AS INT) AS 'FLOAT-TO-INT'
SELECT CAST(7 AS FLOAT) AS 'INT-TO-FLOAT'
SELECT CAST(7 AS varchar) AS 'FLOAT-TO-VARCHAR'


-- FORMAT
-- SELECT FORMAT(VALUE, FORMAT)

-- 1) NUMERIC
SELECT FORMAT(1000, 'N')
SELECT FORMAT(1000, 'G')

-- 2) PERSONALIZED

SELECT FORMAT(1234567899, '##-####-####') -- CAUTION: NOT FIXED!

-- 3) DATE TYPE
SELECT FORMAT(CAST('07/12/2001' AS datetime), 'dd/MMMM/yy')
SELECT FORMAT(CAST('07/12/2001' AS datetime), 'dd/MM/yy')
SELECT FORMAT(CAST('07/12/2001' AS datetime), 'ddd')

-- Exmample:
SELECT 'The product expires on ' + FORMAT(CAST('07/12/2001' AS datetime), 'dd/MMMM/yyyy')