


-- TRIM, LTRIM, RTRIM
DECLARE @name VARCHAR(100) = '   Caroline Ferreira'

SELECT TRIM(@name) AS 'TRIM', DATALENGTH(TRIM(@name)) AS 'TRIM_LENGTH'
SELECT LTRIM(@name) AS 'LTRIM', DATALENGTH(LTRIM(@name)) AS 'LTRIM_LENGTH'
SELECT RTRIM(@name) AS 'RTRIM', DATALENGTH(RTRIM(@name)) AS 'RTRIM_LENGTH'